### ISSUE TITLE
I checkout  zk8-jpa, and mvn clean package

### ISSUE THREAD

**Issue by timloo0710** [zkoss/zkessentials#3]
It can make war ,  but show the following errors, 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2:single (webapp) on project essentials: Error reading assemblies: Error locating assembly descriptor: assembly/webapp.xml
[ERROR] 
[ERROR] [1] [INFO] Searching for file location: /home/timloo/mvn-java-web/zkessentials/assembly/webapp.xml
[ERROR] 
[ERROR] [2] [INFO] File: /home/timloo/mvn-java-web/zkessentials/assembly/webapp.xml does not exist.
[ERROR] 
[ERROR] [3] [INFO] File: /home/timloo/mvn-java-web/zkessentials/assembly/webapp.xml does not exist.
[ERROR] -> [Help 1]
[ERROR] 

But mvn jetty:run  can work!!

**Comment by hawkchen** [comment]
Thanks for report. I have fixed it.
